/**
 * Constants to be accessed throughout application
 */

score.constants = {
	API_NEWS: '/bio/news/index',
	API_LOCATION: '/score/location',
	API_ITSAS_REEOS: '/score/service/itsas/reeos',
	API_ITSAS_EOS: '/score/service/itsas/eos',
	API_ITSAS_RETIREFLOATER: '/score/service/itsas/retirefloater',
	API_ITSAS_SCAN: '/score/service/itsas/scan',
	API_ITSAS_ASSERT_ITM_STATUS: '/score/service/itsas/assertitmstatus',
	API_ITSAS_DELEGATION: '/score/service/itsas/delegation',
	API_ITSAS_POPOUT_DELEGATION: '/score/service/itsas/popoutdelegation',
	API_ITSAS_CREATE_AOS: '/score/service/itsas/createaos',
	API_OSSUPPORT: '/score/osdefinition',
	API_SAT_UPDATE: '/score/audit/update',
	API_TODO_ASSERT: '/score/todos/static',
	API_TODOS: '/score/todos/definition',
	API_USER: '/bio/user',
	APP_DEFAULT: "bio-home",
	DIALOG_LOCATIONS: '/score/index/administration-locationdialog',
	DIALOG_NEWS: '/bio/index/administration-newsdialog',
	DIALOG_OSSUPPORT: '/score/index/administration-ossupportdialog',
	DIALOG_TODOS: '/score/index/administration-tododefinitiondialog',
	DIALOG_USERS: '/bio/index/administration-usersdialog',
	DIJIT_THEME: 'claro',
	ERROR_GENERIC_ERROR: 'There was an error. Please try again.',
	ERROR_UNKNOWN_ACTION: 'Unable to determine requested action.',
	ERROR_INVALID_SELECTION: 'You did not make a valid selection. Please try again.',
	ERROR_NO_APAR_DATA: 'Unable to fetch APAR information.',
	EVENT_HASH_CHANGE: '/dojo/hashchange',
	EVENT_PROFILE_CHANGE: '/score/profilechange',
	IMG_LOADING_BIG: '<img src="/score/ui/custom/images/big_loading.gif" height="100" width ="100" style="padding: 100px 250px 100px 250px" />',
	IMG_LOADING_SMALL: '<img src="/bio/ui/custom/images/mozilla_blu.gif" height="16" width="16" align="left" />',
    PROFILE_HIDE: false,
    PROFILE_SHOW: true,
	SEARCH_ADVANCED: '/score/search/advanced',
	SEARCH_APARS: '/score/search/apars',
	SEARCH_APPLICATION: '/score/search/application',
	SEARCH_BASE: '/score/search',
	SEARCH_EAMT: '/score/search/eamt',
	SEARCH_ITSAS: '/score/search/itsas',
	SEARCH_PACKAGE: '/score/search/package',
	SEARCH_PROCESS: '/score/search/process',
	SEARCH_QUICK: '/score/search/quick',
	SEARCH_SCORE: '/score/search/score',
	SEARCH_UNDOCUMENTED: '/score/search/undocumented',
	SEARCH_UPCOMING_APARS_DETAILS: '/score/search/upcoming-apars/details',
	SEARCH_USER_SAVED: '/score/search/usersaved',
	STATISTICS_DIALOG_SUMMARY: '/score/statistics/dialog/summary',
	STATISTICS_DIALOG_DETAIL: '/score/statistics/dialog/detail',
	STORE_APARGROUP: '/score/report/store/apargroup',
	STORE_COMPLETE: '/score/search/store/complete',
	STORE_EAMT: '/score/search/store/eamt',
	STORE_EXECUTIVES: '/score/bluepages/store/executive',
	STORE_ITM_ORGS: '/score/report/store/itmorg',
	STORE_ITSAS: '/score/search/store/itsas',
	STORE_FEDDB: '/score/search/store/feddb',
	STORE_POOLS: '/score/search/store/pools',
	STORE_GROUPS: '/score/search/store/groups',
	STORE_SCHEDULES: '/score/search/store/schedules',
	STORE_SCORE: '/score/search/store/score',
	STORE_SOFTWARE: '/score/search/store/software',
	STORE_POOL_CRITERIA: '/score/report/store/poolcriteria',
	STORE_POOL_ORGS: '/score/report/store/poolorgs',
	STORE_POOL_NAMES: '/score/report/store/poolnames',
	STORE_POOL_OWNERS: '/score/report/store/poolowners',
	STORE_GROUP_NAMES: '/score/report/store/groupnames',
	STORE_POOL_PRODUCTS: '/score/report/store/poolproducts',
	STORE_POOL_SUBPRODUCTS: '/score/report/store/poolsubproducts',
	STORE_POOL_USAGE: '/score/report/store/poolusages',
	STORE_UNDOCUMENTED: '/score/search/store/undocumented',
	STORE_VIEWS: '/score/report/store/view',
	STORE_BLUEPAGES: '/score/search/store/bluepages',
	STORE_SAVED_ITSAS: '/score/search/store/saveditsas',
	STORE_SAVED_EAMT: '/score/search/store/savedeamt',
	STORE_SAVED_SCORE: '/score/search/store/savedscore',
	URL_ADD_CREDENTIALS: '/score/host/credentials/add',
	URL_ADD_HOST_COMMENT: '/score/host/comments/commentadd',
	URL_ARCHIVE_WINSECINFO: '/score/host/winsecinfoarchive/archive',
	URL_CONTROLLED_ENVS: '/score/report/controlled',
	URL_EXPLAIN_TCPIP_SCAN: '/score/host/scans/explaintcpipscan',
	URL_EXPLAIN_SCM_SCAN: '/score/host/scans/explainscmscan',
	URL_FEDDB_POOL_ASSIGN: '/score/search/feddb/submitassign',
	URL_FEDDB_POOL_SAVE: '/score/scheduling/pooling/save',
	URL_POOL_GROUP_ASSIGN: '/score/search/groups/assign',
	URL_HELPDESK_CREATE_TICKET: '/score/helpdesk/ticket',
	URL_IBMI_LDAP_GET_ACCOUNTS: '/score/service/ibmildap/getaccounts',
	URL_IBMI_LDAP_SET_DIALOG: '/score/service/ibmildap/setdialog',
	URL_IBMI_LDAP_UPDATE_ACCOUNTS: '/score/service/ibmildap/updateaccounts',
	URL_IBMI_LDAP_VALIDATE_PASSWORD: '/score/service/ibmildap/validate',
	URL_ITSAS_API_EOS: '/score/itsas/api/command/eos',
	URL_ITSAS_API_INACTIVE: '/score/itsas/api/command/inactive',
	URL_ITSAS_API_RETIRE_FLOATER: '/score/itsas/api/command/retirefloater',
	URL_ITSAS_API_SCAN_STEP: '/score/itsas/api/command/scan',
	URL_PROFILE_CHANGE: '/bio/index/switchprofile',
	URL_ACCEPT_PENDING_CONTROLLED_ENVIRONMENT: '/score/controlled/update/acceptpending',
	URL_REJECT_PENDING_CONTROLLED_ENVIRONMENT: '/score/controlled/update/rejectpending',
	URL_UPDATE_CONTROLLED_ENVIRONMENT: '/score/controlled/update/controlledupdate',
	URL_REMOVE_FROM_CONTROLLED_ENVIRONMENT: '/score/controlled/update/remove',
	URL_REVALIDATE_CONTROLLED_ENVIRONMENT: '/score/controlled/update/revalidate',
	URL_REMOVE_CREDENTIALS: '/score/host/credentials/remove',
	URL_REPORT_BASE: '/score/report/',
	URL_SAT_UPLOAD: '/score/audit/dialog/sat-upload',
	URL_SCHEDULING_SAVE: '/score/scheduling/index/save',
	URL_SCHEDULING_VALIDATE: '/score/scheduling/index/validate',
	URL_SCHEDULING_REMOVE: '/score/scheduling/index/remove',
	URL_SCHEDULING_UNDO: '/score/scheduling/index/undo',
	URL_SCHEDULING_APPROVE: '/score/scheduling/index/approve',
	URL_SCHEDULING_REJECT: '/score/scheduling/index/reject',
	URL_PUR_APPROVE: '/score/pur/approvals/approve',
	URL_PUR_REJECT: '/score/pur/approvals/reject',
	URL_TICKET_DIALOG: '/score/ticket/index/dialog',
	URL_TICKET_SUBMIT: '/score/ticket/index',
	URL_TODOS_ASSERT: '/score/todos/assert',
	URL_UPDATE_APAR_GROUP: '/score/host/apargroup/apargroupupdate',
	URL_UPDATE_CONFIDENTIAL_FLAG: '/score/host/confidential/confidentialupdate',
	URL_UPDATE_DEVELOPMENT_CONTACT: '/score/host/contact/update',
	URL_UPDATE_HOST_LOCATION: '/score/host/location/update',
	URL_UPDATE_INFRASTRUCTURE: '/score/host/infrastructure/update',
	URL_UPDATE_PROPERTIES: '/score/host/properties/update',
	URL_UPDATE_SAV: '/score/host/services/updatesav',
	URL_UPDATE_SUPPORT: '/score/host/support/update',
	URL_UPDATE_WSUS: '/score/host/services/updatewsus',
	URL_VMWARE_AUTOMATION_ENROLL: '/score/host/vmwareautomation/enroll',
	URL_VMWARE_AUTOMATION_REMOVE: '/score/host/vmwareautomation/remove',
	URL_VMWARE_GUEST: '/score/vmware/guests',
	URL_VMWARE_REGISTER: '/score/vmware/registerguest',
	URL_CLOUD_SAVE_PROJECT: '/score/cloud/projects/save',
	URL_LOGIN_REQUEST: '/bio/login/index/email'
};

